---
title: "Mixed-Effects Model Simulation"
author: "Very Normal"
output: pdf_document
---

```{r}
library(tidyverse)
library(MASS) # for multivariate normal
```

# Random intercept

```{r}
J = 10                # number of individuals
n_j = 30              # number of observations per individual 
sigma_b = 5           # variance of the random intercept
sigma_e = 1           # variance of the random noise
fixed_effect = 1      # population-level effect
fixed_intercept = 5   # population-level intercept

data = tibble(
  subject_id = 1:J,
  
  # Generate subject-specific intercept deviations
  b_i = rnorm(J, mean = 0, sd = sigma_b),
  
  # Generate uniform predictor (easier to visualize)
  X = map(subject_id, function(id) {
    runif(n_j, min = 0, max = 10)
  }), 
  
  # Generate outcome from predictor & subject-specific intercept
  Y = map2(b_i, X, function(bi0, x) {
    (fixed_intercept + bi0) + fixed_effect  * x + rnorm(n_j, mean = 0, sd = sigma_e)
  }) 
) |> 
  unnest(c(X, Y))

data |> 
  ggplot(aes(x = X, y = Y, group = subject_id, color = factor(subject_id))) + 
  geom_point(alpha = 0.5) +
  geom_smooth(method = lm, se = F) + 
  theme_minimal() + 
  theme(legend.position = "bottom")
```


# Random intercept and slope

```{r}
J = 10                                  # number of individuals
n_j = 30                                # number of observations per individual 
G = matrix(c(10, 0, 
             0, 10), nrow = 2)          # covariance matrix of random-effects
fixed_effect = 1                        # population-level effect
fixed_intercept = 5                     # population-level intercept

# Generate random effects first from multivariate normal
random_effects = mvrnorm(J, mu = c(0, 0), Sigma = G) |> as_tibble()
names(random_effects) = c("b_i0", "b_i1")

data = random_effects |> 
  mutate(
    subject_id = 1:J,
    X = map(subject_id, function(id) {
      runif(n_j, min = 0, max = 10)
    }), 
    
    # Generate outcome from predictor & subject-specific intercept and slope
    Y = pmap(list(b_i0, b_i1, X), function(bi0, bi1, x) {
      (fixed_intercept + bi0) + 
        (fixed_effect + bi1)  * 
        x + rnorm(n_j, mean = 0, sd = sigma_e)
    }) 
  ) |> 
  unnest(c(X, Y))

data |> 
  ggplot(aes(x = X, y = Y, group = subject_id, color = factor(subject_id))) + 
  geom_point(alpha = 0.5) +
  geom_smooth(method = lm, se = F) + 
  theme_minimal() + 
  theme(legend.position = "bottom")
```